import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import About from "../components/About";
import Contact from "../components/Contact";
import Main from "../components/Main";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

const messageData = {
  message: {
    chat: { id: process.env.CHAT_ID },
    text: "Привет, ботик! Приложение запустилось",
  },
};

export default function Home() {
  console.log(process.env.CHAT_ID, process.env.BOT_URL);
  useEffect(() => {
    const fetchData = async () => {
      const responseJSON = await fetch(process.env.BOT_URL, {
        method: "POST",
        mode: "no-cors",
        headers: {
          "Content-Type": "application/json",
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: JSON.stringify({
          message: {
            chat: { id: process.env.CHAT_ID },
            text: "Привет, ботик! Приложение запустилось снова опять!",
          },
        }),
      });
      console.log(responseJSON);
    };

    fetchData().catch(console.error);
    console.log(JSON.stringify(messageData));
  }, []);

  return (
    <div>
      <Head>
        <title>Averkiev Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </div>
  );
}
